### ISSUE TITLE
suggesting coauthors generates output which is not copy/pastable

### ISSUE THREAD

**Issue by davidalpert** [davidalpert/go-git-mob#106]
**Describe the bug**
When I run the `git suggest-coauthors` command it spits out a list of commands I can use to add coauthors.

See [this example](https://github.com/davidalpert/go-git-mob/blob/v0.9.2/features/git-mob/suggest-coauthors.feature#L29-L41) from the feature specs:
```
Here are some suggestions for coauthors based on existing authors of this repository:

git mob add-coauthor AD Amy Doe amy@findmypast.com
git mob add-coauthor BD Bob Doe bob@findmypast.com
git mob add-coauthor JD Jane Doe jane@example.com

Paste any line above.
```

- [x] Those capital initials should be lowercase for easier typing, or the casing made configurable with lowercase as a default.
- [x] Those names should be wrapped in quotes:
```
Here are some suggestions for coauthors based on existing authors of this repository:

git add-coauthor ad "Amy Doe" amy@findmypast.com
git add-coauthor bd "Bob Doe" bob@findmypast.com
git add-coauthor jd "Jane Doe" jane@example.com

Paste any line above.
```
 
so that any of the lines is actually pasteable.

for extra credit:
- [x] ignore any coauthors already present in the `~/.git-coauthors` file
- [x] print a different message (🎉 Congrats!, etc) if no missing authors are found
- [x] group real emails separate from (and preceding) anonymous github emails like
```
someone@users.noreply.github.com
```

**Comment by justinechiu** [comment]
Update to:
```
git add-coauthor AD Amy Doe amy@findmypast.com
git add-coauthor BD Bob Doe bob@findmypast.com
git add-coauthor JD Jane Doe jane@example.com
```
