### ISSUE TITLE
🐛 Bug: co-authors not cleared from message template when returning to git solo

### ISSUE THREAD

**Issue by davidalpert** [davidalpert/go-git-mob#88]
**Describe the bug**

**To Reproduce**
1. Install `go-git-mob`
2. Start mobbing
```
git mob ad
```
3. Stop mobbing
```
git solo
```

**Expected behavior**
The mob configuration has been reset and I can make new commits without any `Co-Authored-By` annotations.

**Actual behavior**
The mob configuration remains in the global git template (e.g. `~/.gitmessage) which is read by VSCode, [Fork](https://www.fork.dev), and other git clients, causing `Co-Authored-By` annotations to appear even though we have returned to solo work.

**Additional context**
As we have basically committed to the `prepare-commit-msg` hook approach, updating the message template seems redundant. I suggest that we remove all updates to the message template.

**Comment by teezzan** [comment]
Can you assign this to me? @davidalpert

**Comment by davidalpert** [comment]
@teezzan this codebase started as a port of the Nodejs `git-mob` tool.

If you have any questions about how the code is organized hit me up here or in slack.

**Comment by davidalpert** [comment]
the code behavior was addressed by https://github.com/davidalpert/go-git-mob/pull/89

https://github.com/davidalpert/go-git-mob/pull/94 addresses the broken feature specs
